[workspace]
authors = ["luxiangze <gyk666@email.swu.edu.cn>"]
channels = ["conda-forge", "bioconda"]
name = "trna"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
locarna = ">=2.0.1,<3"
biopython = ">=1.85,<2"
pandas = ">=2.3.0,<3"
rich = ">=14.0.0,<15"
typer = ">=0.16.0,<0.17"
python = ">=3.12.11,<3.13"
beautifulsoup4 = ">=4.13.4,<5"
